name: airplane_thoriq
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.5
  google_fonts: ^2.1.0
  qr_code_scanner: ^1.0.1
  mysql1: ^0.20.0
  sqflite: ^2.0.0
  http: ^0.13.6
  dio: ^4.0.0
  crypto: ^3.0.0
  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
assets:
  - assets/
